name: Backup Firestore

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

env:
  PROJECT_ID: prihlasky-na-tabor
  BUCKET: gs://prihlasky-na-tabor.appspot.com

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PRIHLASKY_NA_TABOR }}
          export_default_credentials: true
      - run: gcloud info
      - run: gcloud config set project $PROJECT_ID
      - run: gcloud firestore export $BUCKET
